# Generated by Django 4.2.1 on 2024-05-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qte', models.IntegerField()),
                ('categorie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_commande.categorie')),
            ],
        ),
    ]
